# Generated by Django 4.0.3 on 2022-03-24 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_book_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.CharField(choices=[('fic', 'Fiction'), ('nfic', 'Non-fiction')], max_length=10),
        ),
    ]
