# Generated by Django 4.0.3 on 2022-03-26 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_alter_book_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='publisher',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
