# Generated by Django 4.0.3 on 2022-03-26 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_rename_author_book_author1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='publisher',
            new_name='publisher1',
        ),
    ]
