# Generated by Django 4.0.3 on 2022-03-26 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='author1',
        ),
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.ManyToManyField(to='main_app.author'),
        ),
    ]
