# Generated by Django 4.0.3 on 2022-03-26 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_remove_book_author1_book_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='author',
            new_name='authors',
        ),
    ]
